app.controller("bookController", ["$scope", function($scope){
	
	$scope.readMore = function(){
		$scope.more = !$scope.more;
	}

	$scope.editBook = function(){
		$scope.showEditWindow = !$scope.showEditWindow;
		$scope.editBookView = !$scope.editBookView;
	}

	// $scope.books = Book.index();

	$scope.books = [
		{"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},
		 {"title":"Sapiens : en kort historik över mänskligheten",
		 "description":"jkasld",
		 "author":"Yuval Noah Harari ",
		 "genre":"Historia & arkeologi",
		 "year":"2015",
		 "isbn":" 9789127140394",
		 "details":"asff"},


	]	
}]);